services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - tp3_httpd1
      - tp3_httpd2
    restart: always
    networks:
      - front_net

  tp3_httpd1:
    image: httpd:2.4
    volumes:
      - ./serveur1/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./serveur1/www/:/var/www/html/
    networks:
      - front_net
      - back1_net

  tp3_php1:
    build: ./php1
    volumes:
      - ./serveur1/www/:/var/www/html/
    networks:
      - back1_net

  tp3_httpd2:
    image: httpd:2.4
    volumes:
      - ./serveur2/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./serveur2/www/:/var/www/html/
    networks:
      - front_net
      - back2_net

  tp3_php2:
    build: ./php2
    volumes:
      - ./serveur2/www/:/var/www/html/
    networks:
      - back2_net

  tp3_mysql1:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass1
      MYSQL_DATABASE: tp3db
      MYSQL_USER: tp3user
      MYSQL_PASSWORD: tp3pass
    volumes:
      - mysql1_data:/var/lib/mysql
      - ./mysql1/:/docker-entrypoint-initdb.d/:ro
    networks:
      - back1_net

  tp3_mysql2:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass2
      MYSQL_DATABASE: tp3db
      MYSQL_USER: tp3user
      MYSQL_PASSWORD: tp3pass
    volumes:
      - mysql2_data:/var/lib/mysql
      - ./mysql2/:/docker-entrypoint-initdb.d/:ro
    networks:
      - back2_net

volumes:
  mysql1_data: {}
  mysql2_data: {}

networks:
  front_net: {}
  back1_net: {}
  back2_net: {}
